<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="1" passed="1">
  <reporter-output>
    <line>
      <![CDATA[Login gets sucessful]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="5716" started-at="2016-11-23T07:35:50Z" finished-at="2016-11-23T07:35:56Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="5716" started-at="2016-11-23T07:35:50Z" finished-at="2016-11-23T07:35:56Z">
      <class name="testCases.Login_with_Valid_Data">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testCases.Login_with_Valid_Data@ef309d]" name="beforeMethod" is-config="true" duration-ms="1670" started-at="2016-11-23T13:05:50Z" finished-at="2016-11-23T13:05:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="Testsc()[pri:0, instance:testCases.Login_with_Valid_Data@ef309d]" name="Testsc" duration-ms="4013" started-at="2016-11-23T13:05:52Z" finished-at="2016-11-23T13:05:56Z">
          <reporter-output>
            <line>
              <![CDATA[Login gets sucessful]]>
            </line>
          </reporter-output>
        </test-method> <!-- Testsc -->
        <test-method status="FAIL" signature="afterMethod()[pri:0, instance:testCases.Login_with_Valid_Data@ef309d]" name="afterMethod" is-config="true" duration-ms="0" started-at="2016-11-23T13:05:56Z" finished-at="2016-11-23T13:05:56Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at testCases.Login_with_Valid_Data.afterMethod(Login_with_Valid_Data.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:703)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- testCases.Login_with_Valid_Data -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
